<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-04RP63D" ignored="1" name="Default test(failed)" tests="3" failures="2" timestamp="2020-01-14T22:00:36 BDT" time="0.062" errors="0">
  <testcase name="exampleTest" time="0.011" classname="testNGExamples.RetryFailedTestCases">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testNGExamples.RetryFailedTestCases.exampleTest(RetryFailedTestCases.java:28)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- exampleTest -->
  <testcase name="testSample" time="0.001" classname="testNGExamples.RetryFailedTestCases">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at testNGExamples.RetryFailedTestCases.testSample(RetryFailedTestCases.java:16)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testSample -->
  <testcase name="testExample" time="0.003" classname="testNGExamples.RetryFailedTestCases"/>
  <testcase name="sampleTest" time="0.0" classname="testNGExamples.RetryFailedTestCases">
    <ignored/>
  </testcase> <!-- sampleTest -->
</testsuite> <!-- Default test(failed) -->
